### ISSUE TITLE
Your Package Might See More Action ;)

### ISSUE THREAD

**Issue by RexWzh** [unioslo/harbor-cli#96]
Hey @pederhan :smile: 

Just a casual chat - your stellar package could become quite the hot spot soon, due to the [Chinese Docker Hub waving goodbye](https://medium.com/@leoli_96098/chinese-docker-hub-complete-shutdown-how-far-can-kubernetes-image-repositories-go-826706007b8e). 

A gentle nudge, hope it's all smooth sailing!

**Comment by pederhan** [comment]
Hi, thank you for informing me! Sorry for the low activity on this package; I have been quite busy the past few months with other things. I'll get better at maintaining the package in the future!
